services:

  app:
    image: rhanmar/devops-for-developers-project-74
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"
    command: ["make", "test"]
    environment:
      DATABASE_NAME: ${{ DATABASE_NAME }}
      DATABASE_USERNAME: ${{ DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ DATABASE_HOST }}
      DATABASE_PORT: ${{ DATABASE_PORT }}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
