name: push.yml
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-buildx-action@v3
      - run: make tests-ci
        working-directory: ./app/

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-buildx-action@v3
      - run: make lint-ci
        working-directory: ./app/

#  build-and-publish:
#    runs-on: ubuntu-latest
#    needs:
#      - lint
#      - tests
#    steps:
#      - run: ls -la
