name: push.yml
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cd app/
      - run: make lint-ci

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cd app/
      - run: make lint-ci

#  build-and-publish:
#    runs-on: ubuntu-latest
#    needs:
#      - lint
#      - tests
#    steps:
#      - run: ls -la
