name: push.yml
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: make setup
        working-directory: ./app/
      - run: make test
        working-directory: ./app/

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: make setup
        working-directory: ./app/
      - run: make lint
        working-directory: ./app/

  build-and-publish:
    runs-on: ubuntu-latest
    needs:
      - lint
      - tests
    steps:
      - name: Use a secret in a script
        run: echo "My secret is not visible in logs"
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build App
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.production
#          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}
#          cache-to: type=inline
          push: true
          tags: rhanmar/devops-for-developers-project-74:latest
